Repository bcarme/app-asso-member, pull requests merged in 2020-07, with the labels that each got.

#1 bootstrap, ukkit, fontawesome, vars and layout
  assets/js/app.js
  assets/scss/_vars.scss
  assets/scss/app.scss
  config/packages/twig.yaml
  package.json
  templates/base.html.twig
  templates/layout.html.twig
  yarn.lock
Labels: reviewed

#3 Fix
  .gitignore
  assets/scss/app.scss
  assets/scss/partials/_vars.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/vich_uploader.yaml
  migrations/Version20200707141457.php
  migrations/Version20200707143302.php
  src/Entity/Delegation.php
  src/Entity/Document.php
  src/Entity/Member.php
  src/Entity/OnlineForm.php
  src/Repository/DelegationRepository.php
  src/Repository/DocumentRepository.php
  src/Repository/MemberRepository.php
  src/Repository/OnlineFormRepository.php
  symfony.lock
  templates/base.html.twig
Labels: reviewed

#27 nav bar, no links
  .gitignore
  assets/scss/app.scss
  assets/scss/partials/_nav.scss
  templates/_nav.html.twig
  templates/base.html.twig
  templates/layout.html.twig
Labels: Changes Requested

#28 fix on color duplicate
  assets/scss/partials/_nav.scss
Labels: reviewed

#29 Us1 us2
  .gitignore
  assets/scss/app.scss
  assets/scss/partials/_security.scss
  assets/scss/partials/_vars.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/security.yaml
  config/packages/twig.yaml
  src/Controller/SecurityController.php
  src/DataFixtures/AppFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/User.php
  src/Form/RegistrationFormType.php
  src/Repository/UserRepository.php
  src/Security/LoginFormAuthenticator.php
  symfony.lock
  templates/_nav.html.twig
  templates/layout.html.twig
  templates/security/login.html.twig
  templates/security/register.html.twig
  translations/security.en.yaml
Labels: Corrections Done

#62 Us14 searchbar
  assets/scss/partials/_trombi.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/kpn_paginator.yaml
  src/Controller/TrombiController.php
  src/Form/TrombiSearchType.php
  src/Repository/MemberRepository.php
  symfony.lock
  templates/trombi/index.html.twig
Labels: Corrections Done
